# Generated by Django 4.1.2 on 2022-10-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game", name="league_type", field=models.CharField(max_length=1),
        ),
    ]
