# Generated by Django 4.1.2 on 2022-10-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_alter_game_league_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ARCLGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("league_type", models.CharField(max_length=1)),
                ("batsmen", models.JSONField()),
                ("bowlers", models.JSONField()),
                ("data", models.JSONField()),
            ],
        ),
    ]
