# Generated by Django 4.1.2 on 2022-10-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_rename_arclgame_arcl_rename_data_arcl_extra_data"),
    ]

    operations = [
        migrations.DeleteModel(name="ARCL",),
        migrations.AddField(
            model_name="game",
            name="batsmen",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="bowlers",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="extra_data",
            field=models.JSONField(default=None, null=True),
        ),
    ]
