# Generated by Django 4.1.2 on 2022-10-21 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_balls"),
        ("game", "0005_delete_arcl_game_batsmen_game_bowlers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="creator",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.profile",
            ),
        ),
    ]
