# Generated by Django 4.1.2 on 2022-10-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0004_profile_pfp_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wins", models.IntegerField(default=0)),
                ("losses", models.IntegerField(default=0)),
                ("draws", models.IntegerField(default=0)),
                ("no_result", models.IntegerField(default=0)),
                (
                    "players",
                    models.ManyToManyField(default=None, null=True, to="users.profile"),
                ),
            ],
        ),
    ]
