# Generated by Django 4.1.2 on 2022-10-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_balls"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="pfp_url",
            field=models.CharField(
                default="https://variety.com/wp-content/uploads/2021/07/Rick-Astley-Never-Gonna-Give-You-Up.png?w=681&h=383&crop=1",
                max_length=500,
            ),
        ),
    ]
