# Generated by Django 4.1.2 on 2022-10-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_team_league_type_team_name"),
        ("users", "0005_profile_teams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="teams",
            field=models.ManyToManyField(default=None, to="teams.team"),
        ),
    ]
